wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.29.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685967203.104822
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 13
      - 23
      4: 3.10.0
      5: 0.15.3
      6: 4.29.1
      8:
      - 3
      - 5
